baidu_ocr:
#  app_id: 35278196
#  api_key: 4NlU2wWq1V0vXSxrx3jdv38j
#  secret_key: b7l98GEx3uN8CXmo8QGHvXTxRBYuC0qU
  app_id: 35971113
  api_key: be7BzHqyoYE99DLv2hGQe16p
  secret_key: LSR5xLRcekY6j0S5xZoIAcNVLq7GKAav